# Generated by Django 5.0.6 on 2024-06-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'FinalGame',
            },
        ),
    ]
