# Generated by Django 5.0.6 on 2024-07-14 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=50)),
                ('player', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[('H', 'House'), ('P', 'Player')], max_length=6)),
                ('match_id', models.CharField(max_length=6)),
                ('level', models.CharField(max_length=6)),
                ('reward_point', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Round Histories',
            },
        ),
    ]
