# Generated by Django 5.0.6 on 2024-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='level',
        ),
        migrations.AddField(
            model_name='history',
            name='point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
