# Generated by Django 5.0.6 on 2024-07-04 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='point', max_length=60, null=True)),
                ('desc', models.CharField(blank=True, default='point', max_length=500, null=True)),
                ('image', models.ImageField(default='points/default.png', upload_to='points/')),
            ],
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='combo_point',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='wallet.combopoint'),
            preserve_default=False,
        ),
    ]
