# Generated by Django 5.0.6 on 2024-07-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_combopoint_paymenthistory_combo_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combopoint',
            name='name',
            field=models.CharField(default='point', max_length=60),
        ),
    ]
