# Generated by Django 5.0.6 on 2024-07-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_combopoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopoint',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
