# Generated by Django 5.0.6 on 2024-07-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_combopoint_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='combopoint',
            name='point',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
