# Generated by Django 5.0.6 on 2024-07-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_combopoint_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='order_type',
        ),
    ]
