# Generated by Django 5.0.6 on 2024-07-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_paymenthistory_combo_point_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combopoint',
            options={'verbose_name_plural': 'Combo Points'},
        ),
    ]
